### ISSUE TITLE
Blank page on upgrade

### ISSUE THREAD

**Issue by inreti** [BobRay/UpgradeMODX#12] opened 2016-04-06 09:16 UTC
On a MODX 2.4.3-pl advanced with core renamend and moved outside of the root, when I choose to upgrade to 2.5.0-rc1 and click on upgrade, I end up with a blank page. I cannot find anything in the logs, not in modx error log and not in apache error log. An empty modx.zip is created in the root. 

UpgradeMODx version is 1.5.0-pl.

**Comment by marcelfischer71** [comment] 2016-04-06 14:23
I think i have a similar problem. I use also UpgradeMODX 1.5.0pl with Revo 2.4.0 and 2.4.2 (traditional, core not outside). I also became a blank page after click on "Upgrade". When i go back to UpgradeMODX 1.2.1rc, the Upgrade works. Changing the Properties (forceFopen, attempts, githubTimeout, modxTimeout) doesn't help.

**Comment by BobRay** [comment] 2016-04-06 14:31
Try changing the ssl_verify_peer property to No. If that works, see the docs on what it means.

**Comment by marcelfischer71** [comment] 2016-04-06 14:48
Ok, tested this too but still get a blank page.

**Comment by Jako** [comment] 2016-04-09 11:41
An fix for open_basedir restricted installations is available with #16

**Comment by emilygraham** [comment] 2016-04-14 12:41
I am getting the same blank page trying to upgrade from 2.4.0 to 2.4.4. An empty MODX.zip file is created at the root. I have a normal setup though and core is not renamed.

 I'm sorry Jako, i don't understand what you mean by 'An fix for open_basedir restricted installations is available with #16' and what the upgrade script is for?

Thanks for your time

**Comment by Jako** [comment] 2016-04-14 13:00
If your host is running with open_basedir restrictions, you should change these lines in https://github.com/BobRay/UpgradeMODX/pull/16/files to solve the creation of an empty modx.zip

**Comment by emilygraham** [comment] 2016-04-14 13:44
Thanks Jako, i will try that as soon as i am able to connect to GitHub and run upgradeMODX. BobRay says to enter a GitHub Token into the github system setting in MODX, but i don't have that system settings so am unsure of how to bypass the errors i get at the moment.

**Comment by emilygraham** [comment] 2016-04-14 15:11
HI Jako, tried the change you suggested in that file, but i still get a blank page when i run the upgrade. Any other ideas?

**Comment by Jako** [comment] 2016-04-14 15:13
No, sorry. Something is disturbing the download. In my case the redirect was not resolved right.

**Comment by emilygraham** [comment] 2016-04-14 17:04
Also my host have confirmed that they don't are not running open_basedir restrictions

**Comment by Jako** [comment] 2016-04-14 18:36
Could your hoster detect why the download does not work? The transfer is running in these lines: https://github.com/Jako/UpgradeMODX/blob/patch-1/core/components/upgrademodx/elements/chunks/upgrademodxsnippetscriptsource.chunk.php#L82-L106

**Comment by BobRay** [comment] 2016-04-14 18:58
I am still working on this. I believe it's because of a change making the cURL option SSL_VERIFYPEER is on by default. If your server doesn't have the information for that process in the right place, cURL will balk. If you want to test that, add this line around line 84 of the upgrademodxscriptsource chunk. (just below the curl_init() line).

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

Be aware that this change exposes you to man-in-the-middle attacks. Theoretically, someone could pretend to be the MODX repo and let you download a malicious file instead of MODX. I think the odds of this are remote, but it's a definite possibility.

A better solution is to correct the root problem:


    Download the cURL [cacert.pem](http://curl.haxx.se/ca/cacert.pem) file and save it to your server
    update php.ini — add curl.cainfo = "PATH_TO/cacert.pem"
    Or add the following and/or similar to your cURL options for each instance:

    curl_setopt($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");   
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

**Comment by emilygraham** [comment] 2016-04-14 21:14
Hi BobRay and Jako, thanks for your responses. What is odd is that i was able to use upgradeMODX to upgrade from 2.2.14 to 2.4.0, without any blank screen. This issue only started occurring when i tried to update from 2.4.0 to 2.4.3 or 2.4.4 (haven't tried 2.4.1 or 2.4.2). If it was something server side, wouldn't it have caused a problem with the original upgrade?

Jako, i have asked the host the question re the transfer, will wait and see what the come back with

I am not totally comfortable with updating and playing around with the files and options you mentioned above BobRay so am thinking that perhaps i should manually update for the time being. I've done a lot of searching online on the merging/copying of files to upgrade and read your instructions, but my host doesn't support extraction of zip files to a directory (cloud hosting and not cpanel).........do i literally copy all the files in the 2.4.4 package to my root directory, overwriting any existing files that are there (excluding the config file)? Are all the resource content and website specific information stored in the database and therefore not overwritten by this process?

Thanks very much for your time.

**Comment by BobRay** [comment] 2016-04-14 23:52
I'm hoping to have a new version out in a day or two. If may fix the
problem, but if not, it has better diagnostics.

If you want to upgrade manually, your description is correct, but
transferring the files individually with FTP often results in missing or
corrupted files.

**Comment by emilygraham** [comment] 2016-04-15 10:20
Thanks BobRay, i will leave it over the weekend and try with the new upgradeMODX when it is released. Would you be able to let me know when you have had a chance to release it?

Many thanks

**Comment by BobRay** [comment] 2016-04-15 20:07
If you subscribe at Bob's Guides <http://bobsguides.com>, you'll get an
email when it's released.

**Comment by emilygraham** [comment] 2016-04-17 18:59
Thanks, i have subscribed and am waiting to receive a confirmation email

**Comment by BobRay** [comment] 2016-04-18 03:11
Version 1.5.1 has been released.

**Comment by emilygraham** [comment] 2016-04-18 10:05
Well, what can i say! That worked like a dream - everything upgraded to MODX 2.4.4 without any problems. Many thanks for your time, help and advice

**Comment by marcelfischer71** [comment] 2016-04-19 07:28
Upgrade works now. Thank you very much!

**Comment by BobRay** [comment] 2016-04-19 18:43
I'm glad that worked for you. :)

**Closed by BobRay** 2016-04-19 18:43 UTC
