### ISSUE TITLE
After updating, UpgradeMODX fails to enter the admin panel. HTTP error ERROR 500

### ISSUE THREAD

**Issue by kos0760** [BobRay/UpgradeMODX#53] opened 2018-11-01 18:45 UTC
Updated UpgradeMODX to version 2.0.2-pl. After that, I can't log in to the modx admin panel. HTTP error ERROR 500

In the server error log: 
```
[error] [client ...] client denied by server configuration: /var/www/.../data/www/.../core/docs/changelog.txt
PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/www/.../data/www/.../core/components/upgrademodx/processors/ugmprocessor.class.php on line 41
```
version of php on the server 5.4.45

It turned out that the problem was in the widget.

**Comment by BobRay** [comment] 2018-11-02 04:02
I don't know what to make of that error. 

This is line 41 of that file:

`public $logFilePath = MODX_CORE_PATH . 'cache/logs/upgrademodx.log';`

The only thing I can think of is that either MODX_CORE_PATH is empty or contains a syntax error, but since it's running from the Manager, I don't see how either condition would be possible.

**Comment by gravino81** [comment] 2018-11-07 15:30
I have the same error after update to latest version 2.0.2-pl

Modx version 2.6.5-pl

Test in PHP Version 5.4.45, 5.6 and 7.1

![schermata 2018-11-07 alle 16 20 12](https://user-images.githubusercontent.com/5929863/48140652-8267ef00-e2a9-11e8-9c05-976563980ea8.png)

**Comment by kos0760** [comment] 2018-11-07 15:47
Thank! I deleted the UpgradeMODX widget from the main page through the database and the site was working. The fact is that on my other sites I updated UpgradeMODX and there were no problems. Only on one site appeared this error, so I am not critical.

**Comment by BobRay** [comment] 2018-11-07 22:31
I think this is the fix for that:  [https://forums.modx.com/thread/104584/upgrademodx-039-versions-empty--check-github-username-039?page=2#dis-post-562586](https://forums.modx.com/thread/104584/upgrademodx-039-versions-empty--check-github-username-039?page=2#dis-post-562586)

I'll be releasing a new version soon.

**Comment by BobRay** [comment] 2018-11-09 23:06
Sorry, I think that fix is incorrect. Watch for the new version.

**Comment by sebastian-marinescu** [comment] 2019-01-22 20:04
Hi @kos0760 @gravino81, 
can you check if this is still happening with "2.1.2-pl"?

**Comment by Plushkin** [comment] 2019-05-07 21:01
Hi, I have the same error after update on Modx version 2.6.5-pl

**Comment by Plushkin** [comment] 2019-05-07 21:06
2.1.2-pl same error (

**Comment by BobRay** [comment] 2019-05-08 22:17
I really thought I'd corrected that in [this commit](https://github.com/BobRay/UpgradeMODX/commit/acf8490e714ed0a26aa687141ecf08f4a9c94ca6).

I haven't been able to duplicate the error on any platform, so I can't troubleshoot it.

**Comment by sturple** [comment] 2019-05-17 21:15
Hi @BobRay 
Don't know if this is the same issue, but here is what i believe might be the cause.
## My setup
- Modx v 2.6.5
- UpgradeMODX plugin v1.5.5 

## How to reproduce
- Upgrade packages
- UpgradeMODX v1.5.5 -> v2.1.2

## What happened
- The admin manager gave a 500 error
- fatal error message Call to undefined method UpgradeMODX::versionListExists() in the upgrademodx snippet.
- In the snippet on line 127  here is the line of code ``` $versionListExists = $upgrade->versionListExists(); ```
- I'm guessing in the core modx they added some functions to the $upgrade class, which are not in earler versions of modx core ie 2.6.5, but is in 2.7.1.

## How I fixed.

- Found old version of upgrademodx snippet, and replaced.
- Remove the version and then Re install upgrademodx 1.5.5
- Upgrade modx 2.7.1
- Upgrade Packages. (upgrademodx to v2.1.2)

**Comment by BobRay** [comment] 2019-05-17 22:07
Is it possible that the error message specified line 106 rather than 126?  

This error is usually caused  by a problem with the News and/or Security feeds on the dashboard. There's a discussion of it in the [troubleshooting section](https://bobsguides.com/upgrade-modx-package.html) of the docs.

**Closed by BobRay** 2019-05-17 22:07 UTC
